### ISSUE TITLE
Add CLI admin api

### ISSUE THREAD

**Issue by EvilLord666** [Wissance/Ferrum#23]
after all works on `Redis` as provider will be finished we have to make admin interface for Ferrum configure

Admin interface must provide following common operations schema: `{operation} {resource} {resource_id} {params} {value}`
1. `{operation}` one of the 4 operation `create`, `update`, `delete`, `get`
2. `{resource}` - name of resource - `realm`, `client`, `user`
3. `{namespace}` - object namespace
4. `{resource_id}` - resource name i.e. name of `realm`, `client`, `user`
5. `{params}` additional params that requires for operations i.e. `realm` for `client` and `user`
6. `{value}` is a `JSON` that contains object value itself

i.e. consider Realm creation:

```ps1
   ferrum-admin --operation=create --resource=realm --namespace=ferrum_2 --resource_id=IRP --value=\"{\"name\" "irp_rt\", ....}\"
``` 

If we provide full `realm` structure with `client` and `user` this data struct should be separated && created all objects at once

if we create a `User` we should operate with public user information (not show credentials), if we run user creation we should query user password && check password

additionally we have 2 additional methods

1. `ferrum-admin --operation=change_password --namespace=ferrum_2 --resource=user --resource_id=admin`
2. `ferrum-admin --operation=reset_password --namespace=ferrum_2 --resource=user --resource_id=admin`

`reset_password` resets password to randomly generated (8 symbols at least)

Techically ferrum-admin should be additional software located in `/ferrum/api/admin/cli`, management operations (except password operations) must be declared in `DataContext` interface

**Comment by EvilLord666** [comment]
minimal `UI` is a cmd line `UI`

**Comment by awsoremod** [comment]
1. А нужен ли логгер для cli, или достаточно в консоль вывода ?
2. Нужно уточнить на счет подключения к redis. Какой файл конфига используем ? Можно отдельный файл конфига для cli только с data_source. Или можно через env. Или можно также параметрами к запуску утилиты.

**Comment by EvilLord666** [comment]
done
