### ISSUE TITLE
Check Realm value passing via path

### ISSUE THREAD

**Issue by EvilLord666** [Wissance/Ferrum#36]
It is possible to pass some non valid data in Realm i.e. pass `sql injection` (now we don't support SQL databases but could do in a future) or something that could harm a server, therefore we must validate text values. Therefore we should add `/api/rest/utilities.go` where we should add `func Validate(strVal string) bool, err`. If param is inavlid we should return `400` error with message like `{ParamName} is Invalid` . 

Realm probably could contains only:
* letters, 
* digits, 
* _  (underscore)
* -  (dash)

However one of SQL injection technique is to pass `sql` commentary --, therefore we must be sure that Realm parameter is safe for our system

**Comment by awsoremod** [comment]
1) Allow writing in unicode?
2) Can there be such a situation. If we have a character consisting of two bytes of the character '-', and it will be written to the database not character by character, but byte by by byte

**Comment by EvilLord666** [comment]
1. In Go all strings are Unicode UTF-8 encoded , therefore Realm is definitely unicode str
2. No, we working with symbols/characters not bytes

**Comment by awsoremod** [comment]
Do only in rest api's need to be checked realm name? When saving a realm to the database, do I need to check if the name is correct?

**Comment by awsoremod** [comment]
Two questions.
1. It may be worth performing this function in middleware. Create?
2. There may be a case when a realm with an incorrect name is stored in the database. Perhaps we should create a constructor for realm and validate the name there?

**Comment by EvilLord666** [comment]
1. No, this should n't be a middleware, because it is possible that not all requests could be related to Realm
2. Probably we should create a `RealmValidator` struct with method:
```go
func (r *data.Realm) Validate() err {
}
``` 
This validator should be used before `Create`/`Update` operations therefore we won't have "bad" Realms

**Comment by EvilLord666** [comment]
Done
