### ISSUE TITLE
Logger could crush app if config is missing or invalid

### ISSUE THREAD

**Issue by EvilLord666** [Wissance/Ferrum#45]
we should check and fix

**Comment by awsoremod** [comment]
Внутри этой функции:
application/application.go
func (app *Application) Init() (bool, error) 

Логгер используется внутри функции в функциях  (внутри этих функций логгер nil):
app.readAppConfig()
app.readKey()

Но логгер создается после использования этих функций.

**Comment by EvilLord666** [comment]
Sure it seems that error is logging to logger but app is not configured yet, probably we should output just with `fmt.Println(msg)`, until `app.logger.Init()` is called

**Comment by EvilLord666** [comment]
Done
